# Source: spark-operator/templates/spark-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  namespace: spark-operator
  labels:
    helm.sh/chart: spark-operator-1.1.3
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "v1beta2-1.2.3-3.1.1"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: spark-spark
  namespace: spark-operator
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
