# Source: spark-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-spark-operator
  namespace: spark-operator
  annotations:
    "helm.sh/hook": pre-install
  labels:
    helm.sh/chart: spark-operator-1.1.3
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/instance: spark
    app.kubernetes.io/version: "v1beta2-1.2.3-3.1.1"
    app.kubernetes.io/managed-by: Helm
